const String kUrlLinkedin =
    'https://www.linkedin.com/in/paksan-makina-ba2648178/';
const String kUrlFacebook = 'https://www.facebook.com/paksanmak/';
const String kUrlYoutube =
    'https://www.youtube.com/channel/UCX-RQBs37hXd-enTaXEKE1A';
const String kUrlInstagram = 'https://www.instagram.com/paksan_makina_/';
const String kBayiSifre = '1970';
const String kUrlLink1= 'http://www.paksanmakina.com.tr/19-23-mart-2019-konya-fuarinda-misafirimiz-olun/';
const String kUrlLink2= 'http://www.paksanmakina.com.tr/paksan-2019-izmir-fuardaydi/';
const String kUrlLink3= 'http://www.paksanmakina.com.tr/yeni-sitemiz-yayinda/';

const String ktextSuper8002 = 'DENEY RAPORLARI SUPERS8002 BALYA MAKİNASI';
const String kButton1TextSuper8002 = 'S8002 2 İPLİ, HAŞBAYSIZ (120) 02.10.2024';
const String kButton2TextSuper8002 = 'S8002E 2 İPLİ, HAŞBAYSIZ (120E) 02.10.2024';
const String kButton3TextSuper8002 = '130-131 DENEY RAPORU 09.06.2020';
const String kButton4TextSuper8002 = 'S8002E 3 İPLİ, HAŞBAYLI (131E) 02.10.2024';
const String kButton5TextSuper8002 = 'S8002E 3 İPLİ, HAŞBAYSIZ (130E) 02.10.2024';
const String kButton6TextSuper8002 = '131D DENEY RAPORU';

const String ktextYunusBalya = 'DENEY RAPORLARI SUPER YUNUS BALYA MAKİNASI';
const String kButton1TextYunusBalya = '220 DENEY RAPORU 09.06.2020';
const String kButton2TextYunusBalya = '230-231 DENEY RAPORU 09.06.2020';
const String kButton3TextYunusBalya = '231D DENEY RAPORU';

const String kTextKvkk = 'KİŞİSEL VERİLERİN KORUNMASI';
const String kButton1TextKvkk = 'PAKSAN KİŞİSEL VERİLERİN İŞLENMESİ VE KORUNMASI POLİTİKASI';
const String kButton2TextKvkk = 'PAKSAN KVKK TEDARİKÇİ&TAŞERON ÇALIŞANI AYDINLATMA METNİ';
const String kButton3TextKvkk = 'PAKSAN KVKK TEDARİKÇİ AYDINLATMA METNİ';
const String kButton4TextKvkk = 'PAKSAN KVKK RIZA METNİ';
const String kButton5TextKvkk = 'PAKSAN KVKK PERSONEL AYDINLATMA METNİ';
const String kButton6TextKvkk = 'PAKSAN KVKK MÜŞTERİ AYDINLATMA METNİ';
const String kButton7TextKvkk = 'PAKSAN KVKK İŞ BAŞVURUSU ADAY PERSONEL AYDINLATMA METNİ';
const String kButton8TextKvkk = 'PAKSAN KVKK VERİ SAHİBİ BAŞVURU FORMU';

const String ktextYemKarma = 'DENEY RAPORLARI YEM KARMA MAKİNASI';
const String kButton1TextYemKarma = '1,5m³ Diamond Yem Karma 17.07.2022';
const String kButton2TextYemKarma = '2m³ Diamond Yem Karma 17.07.2022';
const String kButton3TextYemKarma = '3m³ Diamond Yem Karma 17.07.2017';
const String kButton4TextYemKarma = '4m³ Pelican Yem Karma';
const String kButton5TextYemKarma = '6m³ Pelican Deney Raporu 17.07.2022';
const String kButton6TextYemKarma = '8m³ Pelican Deney Raporu';

const String kTextTeknikSartnameler = 'TEKNİK ŞARTNAMELER';
const String kButton1TextTeknikS = 'DİĞER ÜRÜNLERİMİZ';
const String kButton2TextTeknikS = 'SÜPER S8002 BALYA MAKİNASI';
const String kButton3TextTeknikS = 'SÜPER YUNUS BALYA MAKİNASI';
const String kButton4TextTeknikS = 'YEM KARMA MAKİNASI';

const String kTextDeneyRaporlari = 'DENEY RAPORLARI';
const String kButton1TextDeneyRaporlari = 'DİĞER ÜRÜNLERİMİZ';
const String kButton2TextDeneyRaporlari = 'SÜPER S8002 BALYA MAKİNASI';
const String kButton3TextDeneyRaporlari = 'SÜPER YUNUS BALYA MAKİNASI';
const String kButton4TextDeneyRaporlari = 'YEM KARMA MAKİNASI';

const String kTextZiraiKredilendirmeBelgeleri = 'ZİRAİ KREDİLENDİRME BELGELERİ';
const String kButton1TextZiraiKredilendirme = 'DİĞER ÜRÜNLERİMİZ';
const String kButton2TextZiraiKredilendirme = 'SÜPER S8002 BALYA MAKİNASI';
const String kButton3TextZiraiKredilendirme = 'SÜPER YUNUS BALYA MAKİNASI';
const String kButton4TextZiraiKredilendirme = 'YEM KARMA MAKİNASI';

const String kTextTSDU = 'TEKNİK ŞARTNAMELER DİĞER ÜRÜNLERİZ';
const String kButton1TextTSDU = 'Çekiç';
const String kButton2TextTSDU = 'Diavel';
const String kButton3TextTSDU = 'Kırlangıç Ot Toplam Makinası';
const String kButton4TextTSDU = 'Orkinos 870';
const String kButton5TextTSDU = 'ORKİNOS 1207';
const String kButton6TextTSDU = 'Scorpion';

const String kTextTSS8002 = 'TEKNİK ŞARTNAMELER SUPER S8002 BALYA MAKİNASI';
const String kButton1TextTSS8002 = '120E-SÜPER S8002 E 2 İPLİ HAŞBAYSIZ';
const String kButton2TextTSS8002 = '120-SÜPER S8002 2 İPLİ HAŞBAYSIZ';
const String kButton3TextTSS8002 = '130E-SÜPER S8002 E 3 İPLİ HAŞBAYSIZ';
const String kButton4TextTSS8002 = '130-SÜPER S8002 3 İPLİ HAŞBAYSIZ';
const String kButton5TextTSS8002 = '131D2-SÜPER S8002 E 3 İPLİ OTOMATİK HAŞBAYLI';
const String kButton6TextTSS8002 = '131D-SÜPER S8002 E 3 İPLİ OTOMATİK HAŞBAYLI';
const String kButton7TextTSS8002 = '131E- SÜPER S8002 E 3 İPLİ HAŞBAYLI';
const String kButton8TextTSS8002 = '131-SÜPER S8002 3 İPLİ HAŞBAYLI';

const String kTextTSYunus = 'TEKNİK ŞARTNAMELER SUPER YUNUS BALYA MAKİNASI';
const String kButton1TextTSYunus = '220-SÜPER YUNUS 2 İPLİ HAŞBAYSIZ';
const String kButton2TextTSYunus = '230-SÜPER YUNUS 3 İPLİ HAŞBAYSIZ';
const String kButton3TextTSYunus = '231D2-SÜPER YUNUS 3 İPLİ OTOMATİK HAŞBAYLI';
const String kButton4TextTSYunus = '231D-SÜPER YUNUS 3 İPLİ OTOMATİK HAŞBAYLI';
const String kButton5TextTSYunus = '231-SÜPER YUNUS 3 İPLİ HAŞBAYLI';

const String kTextTSYemKarma = 'TEKNİK ŞARTNAMELER YEM KARMA MAKİNASI';
const String kButton1TextTSYemKarma = '4m³ ÇE Pelican';
const String kButton2TextTSYemKarma = '4m³ Pelican';
const String kButton3TextTSYemKarma = '6m³ Pelican';
const String kButton4TextTSYemKarma = '8m³ Pelican';

const String kTextZKDU = 'ZİRAİ KREDİLENDİRME BELGELERİ DİĞER ÜRÜNLERİMİZ';
const String kButton1TextZKDU = 'ÇEKİÇ (HAMMER) MODEL BALYA MAKİNASI 14.03.2023' ;
const String kButton2TextZKDU = 'ORKİNOS 6 İPLİ HAŞPAYLI HAŞPAYSIZ ZİRAİ KR. 14.09.2020';
const String kButton3TextZKDU = 'ORKİNOS 4 İPLİ BÜYÜK PRİZMATİK TİP BALYA MAKİNASI 18.03.2024';

const String kTextZKSuperS8002 = 'ZİRAİ KREDİLENDİRME BELGELERİ SUPER S8002 BALYA MAKİNASI';
const String kButton1TextZKSuperS8002 = 'S8002 DUAL (131D) 04.08.2022' ;
const String kButton2TextZKSuperS8002 = 'S8002 3 İPLİ HAŞPAYLI HAŞPAYSIZ(130-131)Zirai Kr. 09.06.2020' ;

const String kTextZKSuperYunus = 'ZİRAİ KREDİLENDİRME BELGELERİ SUPER YUNUS BALYA MAKİNASI';
const String kButton1TextZKSuperYunus = 'YUNUS 3 İPLİ HAŞPAYLI-HAŞPAYSIZ(230-231) Zirai Kr. 09.06.2020' ;
const String kButton2TextZKSuperYunus = 'YUNUS 2 İPLİ HAŞPAYSIZ (220) Zirai Kr. 09.06.2020' ;
const String kButton3TextZKSuperYunus = 'YUNUS DUAL (231D) 14.07.2022 ' ;

const String kTextZKYemKarma = 'ZİRAİ KREDİLENDİRME BELGELERİ YEM KARMA MAKİNASI';
const String kButton1TextZKYemKarma = '8m³ Pelican Yatay Yem Karma' ;
const String kButton2TextZKYemKarma = 'PELİCAN 4M3 YEM KARMA 13.02.2022' ;
const String kButton3TextZKYemKarma = '1,5 M³ DIAMOND 17.07.2022' ;
const String kButton4TextZKYemKarma = '2 M³ DIAMOND 17.07.2022' ;
const String kButton5TextZKYemKarma = '3 M³ DIAMOND 17.07.2022' ;
const String kButton6TextZKYemKarma = '6 M³ PELICAN 17.07.2022' ;

const String kPdfAssetKvkk1 = 'images/kvkk1.pdf';
const String kPdfAssetKvkk2 = 'images/kvkk2.pdf';
const String kPdfAssetKvkk3 = 'images/kvkk3.pdf';
const String kPdfAssetKvkk4 = 'images/kvkk4.pdf';
const String kPdfAssetKvkk5 = 'images/kvkk5.pdf';
const String kPdfAssetKvkk6 = 'images/kvkk6.pdf';
const String kPdfAssetKvkk7 = 'images/kvkk7.pdf';
const String kPdfAssetKvkk8 = 'images/kvkk8.pdf';
const String kPdfAssetYerliMali = 'images/yerlimali.pdf';
const String kPdfAssetCekic = 'images/cekic.pdf';
const String kPdfAssetKirlangic = 'images/kirlangic.pdf';
const String kPdfAssetOrkinos870 = 'images/orkinos870.pdf';
const String kPdfAssetOrkinos6127 = 'images/orkinos6127.pdf';
const String kPdfAssetYengec135 = 'images/yengec135.pdf';
const String kPdfAssetYengec165 = 'images/yengec165.pdf';
const String kPdfAssetYengec195 = 'images/yengec195.pdf';
const String kPdfAssetS8002_1 = 'images/S8002_2_ipli_hasbaysiz_120.pdf';
const String kPdfAssetS8002_2 = 'images/S8002E_2_ipli_hasbaysiz_120e.pdf';
const String kPdfAssetS8002_3 = 'images/130_131_deney_raporu.pdf';
const String kPdfAssetS8002_4 = 'images/S8002E_3_ipli_hasbayli_131e.pdf';
const String kPdfAssetS8002_5 = 'images/S8002E_3_ipli_hasbaysiz_130e.pdf';
const String kPdfAssetS8002_6 = 'images/131D_deney_raporu.pdf';
const String kPdfAssetYunusBalya1 = 'images/220_deney_raporu.pdf';
const String kPdfAssetYunusBalya2 = 'images/230_231_deney_raporu.pdf';
const String kPdfAssetYunusBalya3 = 'images/231D_deney_raporu.pdf';
const String kPdfAssetYemKarma1 = 'images/15m3_diamond.pdf';
const String kPdfAssetYemKarma2 = 'images/2m3_diamond.pdf';
const String kPdfAssetYemKarma3 = 'images/3m3_diamond.pdf';
const String kPdfAssetYemKarma4 = 'images/4m3_pelican.pdf';
const String kPdfAssetYemKarma5 = 'images/6m3_pelican_deney_raporu.pdf';
const String kPdfAssetYemKarma6 = 'images/8m3_pelican_deney_raporu.pdf';
const String kPdfAssetTSDU1 = 'images/tscekic.pdf';
const String kPdfAssetTSDU2 = 'images/tsDiavel.pdf';
const String kPdfAssetTSDU3 = 'images/tskirlangic.pdf';
const String kPdfAssetTSDU4 = 'images/tsorkinos870.pdf';
const String kPdfAssetTSDU5 = 'images/tsorkinos1207.pdf';
const String kPdfAssetTSDU6 = 'images/tsscorpion.pdf';
const String kPdfAssetTSS8002_1 = 'images/120e_super_s8002_e_2_ipli_hasbaysiz.pdf';
const String kPdfAssetTSS8002_2 = 'images/120-super_s8002_2_ipli_hasbaysiz.pdf';
const String kPdfAssetTSS8002_3 = 'images/130e_super_s8002_e_3_ipli_hasbaysiz.pdf';
const String kPdfAssetTSS8002_4 = 'images/130_super_s8002_3_ipli_hasbaysiz.pdf';
const String kPdfAssetTSS8002_5 = 'images/131d2_super_s8002_e_3_ipli_otomatik_hasbayli.pdf';
const String kPdfAssetTSS8002_6 = 'images/131d_super_s8002_e_3_ipli_otomatik_hasbayli.pdf';
const String kPdfAssetTSS8002_7 = 'images/131e_super_s8002_e_3_ipli_hasbayli.pdf';
const String kPdfAssetTSS8002_8 = 'images/131_super_s8002_3_ipli_hasbayli.pdf';
const String kPdfAssetTSYunus1 = 'images/220_super_yunus_2_ipli_hasbaysiz.pdf';
const String kPdfAssetTSYunus2 = 'images/230_super_yunus_3_ipli_hasbaysiz.pdf';
const String kPdfAssetTSYunus3 = 'images/231d2_super_yunus_3_ipli_otomatik_hasbayli.pdf';
const String kPdfAssetTSYunus4 = 'images/231d_super_yunus_3_ipli_otomatik_hasbayli.pdf';
const String kPdfAssetTSYunus5 = 'images/231_super_yunus_3_ipli_hasbayli.pdf';
const String kPdfAssetTSYemKarma1 = 'images/4m3_ce_pelican.pdf';
const String kPdfAssetTSYemKarma2 = 'images/ts_4m3_pelican.pdf';
const String kPdfAssetTSYemKarma3 = 'images/6m3_pelican.pdf';
const String kPdfAssetTSYemKarma4 = 'images/8m3_pelican.pdf';
const String kPdfAssetZKDigerUrunler1 = 'images/cekic_hammer_model.pdf';
const String kPdfAssetZKDigerUrunler2 = 'images/orkinos_6_ipli_haspayli_haspaysiz.pdf';
const String kPdfAssetZKDigerUrunler3 = 'images/orkinos_4_ipli_buyuk_prizmatik_tip.pdf';
const String kPdfAssetZKSuperYunus1= 'images/yunus_3_ipli_haspayli_haspaysiz.pdf';
const String kPdfAssetZKSuperYunus2= 'images/yunus_2_ipli_haspaysiz_220.pdf';
const String kPdfAssetZKSuperYunus3= 'images/yunus_dual_231d.pdf';
const String kPdfAssetZKYemKarma1= 'images/8m3_pelican_yatay_yem_karma.pdf';
const String kPdfAssetZKYemKarma2= 'images/pelican_4m3_yem_karma.pdf';
const String kPdfAssetZKYemKarma3= 'images/15_m3_diamond.pdf';
const String kPdfAssetZKYemKarma4= 'images/zk_2_m3_diamond.pdf';
const String kPdfAssetZKYemKarma5= 'images/zk_3_m3_diamond.pdf';
const String kPdfAssetZKYemKarma6= 'images/zk_6_m3_pelican.pdf';



const String kPdfKvkk1 = 'kvkk1.pdf';
const String kPdfKvkk2 = 'kvkk2.pdf';
const String kPdfKvkk3 = 'kvkk3.pdf';
const String kPdfKvkk4 = 'kvkk4.pdf';
const String kPdfKvkk5 = 'kvkk5.pdf';
const String kPdfKvkk6 = 'kvkk6.pdf';
const String kPdfKvkk7 = 'kvkk7.pdf';
const String kPdfKvkk8 = 'kvkk8.pdf';
const String kPdfYerliMali = 'yerlimali.pdf';
const String kPdfCekic = 'cekic.pdf';
const String kPdfKirlangic = 'kirlangic.pdf';
const String kPdfOrkinos870 = 'orkinos870.pdf';
const String kPdfOrkinos6127 = 'orkinos6127.pdf';
const String kPdfYengec135 = 'yengec135.pdf';
const String kPdfYengec165 = 'yengec165.pdf';
const String kPdfYengec195 = 'yengec195.pdf';
const String kPdfS8002_1 = 'S8002_2_ipli_hasbaysiz_120.pdf';
const String kPdfS8002_2 = 'S8002E_2_ipli_hasbaysiz_120e.pdf';
const String kPdfS8002_3 = '130_131_deney_raporu.pdf';
const String kPdfS8002_4 = 'S8002E_3_ipli_hasbayli_131e.pdf';
const String kPdfS8002_5 = 'S8002E_3_ipli_hasbaysiz_130e.pdf';
const String kPdfS8002_6 = '131D_deney_raporu.pdf';
const String kPdfYunusBalya1 = '220_deney_raporu.pdf';
const String kPdfYunusBalya2 = '230_231_deney_raporu.pdf';
const String kPdfYunusBalya3 = '231D_deney_raporu.pdf';
const String kPdfYemKarma1 = '15m3_diamond.pdf';
const String kPdfYemKarma2 = '2m3_diamond.pdf';
const String kPdfYemKarma3 = '3m3_diamond.pdf';
const String kPdfYemKarma4 = '4m3_pelican.pdf';
const String kPdfYemKarma5 = '6m3_pelican_deney_raporu.pdf';
const String kPdfYemKarma6 = '8m3_pelican_deney_raporu.pdf';
const String kPdfTSDU1 = 'tscekic.pdf';
const String kPdfTSDU2 = 'tsDiavel.pdf';
const String kPdfTSDU3 = 'tskirlangic.pdf';
const String kPdfTSDU4 = 'tsorkinos870.pdf';
const String kPdfTSDU5 = 'tsorkinos1207.pdf';
const String kPdfTSDU6 = 'tsscorpion.pdf';
const String kPdfTSS8002_1 = '120e_super_s8002_e_2_ipli_hasbaysiz.pdf';
const String kPdfTSS8002_2 = 'super_s8002_2_ipli_hasbaysiz.pdf';
const String kPdfTSS8002_3 = '130e_super_s8002_e_3_ipli_hasbaysiz.pdf';
const String kPdfTSS8002_4 = '130_super_s8002_3_ipli_hasbaysiz.pdf';
const String kPdfTSS8002_5 = '131d2_super_s8002_e_3_ipli_otomatik_hasbayli.pdf';
const String kPdfTSS8002_6 = '131d_super_s8002_e_3_ipli_otomatik_hasbayli.pdf';
const String kPdfTSS8002_7 = '131e_super_s8002_e_3_ipli_hasbayli.pdf';
const String kPdfTSS8002_8 = '131_super_s8002_3_ipli_hasbayli.pdf';
const String kPdfTSYunus1 = '220_super_yunus_2_ipli_hasbaysiz.pdf';
const String kPdfTSYunus2 = '230_super_yunus_3_ipli_hasbaysiz.pdf';
const String kPdfTSYunus3 = '231d2_super_yunus_3_ipli_otomatik_hasbayli.pdf';
const String kPdfTSYunus4 = '231d_super_yunus_3_ipli_otomatik_hasbayli.pdf';
const String kPdfTSYunus5 = '231_super_yunus_3_ipli_hasbayli.pdf';
const String kPdfTSYemKarma1 = '4m3_ce_pelican.pdf';
const String kPdfTSYemKarma2 = 'ts_4m3_pelican.pdf';
const String kPdfTSYemKarma3 = '6m3_pelican.pdf';
const String kPdfTSYemKarma4 = '8m3_pelican.pdf';
const String kPdfZKDigerUrunler1 = 'çekic_hammer_model.pdf';
const String kPdfZKDigerUrunler2 = 'orkinos_6_ipli_haspayli_haspaysiz.pdf';
const String kPdfZKDigerUrunler3 = 'orkinos_4_ipli_buyuk_prizmatik_tip.pdf';
const String kPdfZKSuperYunus1 = 'yunus_3_ipli_haspayli_haspaysiz.pdf';
const String kPdfZKSuperYunus2 = 'yunus_2_ipli_haspaysiz_220.pdf';
const String kPdfZKSuperYunus3 = 'yunus_dual_231d.pdf';
const String kPdfZKYemKarma1 = '8m3_pelican_yatay_yem_karma.pdf';
const String kPdfZKYemKarma2 = 'pelican_4m3_yem_karma.pdf';
const String kPdfZKYemKarma3 = '15_m3_diamond.pdf';
const String kPdfZKYemKarma4 = 'zk_2_m3_diamond.pdf';
const String kPdfZKYemKarma5 = 'zk_3_m3_diamond.pdf';
const String kPdfZKYemKarma6 = 'zk_6_m3_pelican.pdf';



String assetPDFYerliMali;
String assetPDFPath1;
String assetPDFPath2;
String assetPDFPath3;
String assetPDFPath4;
String assetPDFPath5;
String assetPDFPath6;
String assetPDFPath7;
String assetPDFPath8;
String assetPDFCekic;
String assetPDFKirlangic;
String assetPDFOrkinos870;
String assetPDFOrkinos6127;
String assetPDFYengec135;
String assetPDFYengec165;
String assetPDFYengec195;
String assetPDFS8002_1;
String assetPDFS8002_2;
String assetPDFS8002_3;
String assetPDFS8002_4;
String assetPDFS8002_5;
String assetPDFS8002_6;
String assetPDFYunusBalya1;
String assetPDFYunusBalya2;
String assetPDFYunusBalya3;
String assetPDFYemKarma1;
String assetPDFYemKarma2;
String assetPDFYemKarma3;
String assetPDFYemKarma4;
String assetPDFYemKarma5;
String assetPDFYemKarma6;
String assetPDFTSDU1;
String assetPDFTSDU2;
String assetPDFTSDU3;
String assetPDFTSDU4;
String assetPDFTSDU5;
String assetPDFTSDU6;
String assetPDFTSS8002_1;
String assetPDFTSS8002_2;
String assetPDFTSS8002_3;
String assetPDFTSS8002_4;
String assetPDFTSS8002_5;
String assetPDFTSS8002_6;
String assetPDFTSS8002_7;
String assetPDFTSS8002_8;
String assetPDFTSYunus1;
String assetPDFTSYunus2;
String assetPDFTSYunus3;
String assetPDFTSYunus4;
String assetPDFTSYunus5;
String assetPDFTSYemKarma1;
String assetPDFTSYemKarma2;
String assetPDFTSYemKarma3;
String assetPDFTSYemKarma4;
String assetPDFZKDigerUrunler1;
String assetPDFZKDigerUrunler2;
String assetPDFZKDigerUrunler3;
String assetPDFZKSuperYunus1;
String assetPDFZKSuperYunus2;
String assetPDFZKSuperYunus3;
String assetPDFZKYemKarma1;
String assetPDFZKYemKarma2;
String assetPDFZKYemKarma3;
String assetPDFZKYemKarma4;
String assetPDFZKYemKarma5;
String assetPDFZKYemKarma6;


const kTextpaksanMotto =
        'Paksan her geçen gün ürün yelpazesini geliştirmeye devam ediyor.Prizmatik balya makinası üretiminin yanı sıra, rulo balya makinaları, yatay ve dikey yem karma makinaları,kendi yürür ve sıra bağımsız silaj makinaları, toprak işleme makinaları ve silaj paketleme makinaları üretimlerini gerçekleştiriyor.';
const kTextPaksaniKesfet = 'Paksan\'ı Keşfedin!';
const kTextPaksanMakina ='Paksan Makina';
const kAssetCiftlik = 'images/Ciftlik.png';
const kTextVerimliUretim = 'Verimli Üretim';
